version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
  server:
    image: zigridar/test-server:3
    ports:
      - 8080:8080
    volumes:
      - ./screens:/app/screens
    depends_on:
      - mongo
